### ISSUE TITLE
Write Vue Quick Start Guide

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/store#11]
We should have an early Quick Start guide [in the style of our Forms docs](https://tanstack.com/form/latest/docs/framework/react/quick-start) that includes a demo codebase for `store` like a counter or something similar.

File to edit: https://github.com/TanStack/store/blob/main/docs/framework/vue/quick-start.md

**Comment by Davidthecode** [comment]
Hi @crutchcorn what demo codebase do you want to use. I could help with that

**Comment by crutchcorn** [comment]
@Davidthecode we just had an example added to the React Quick Start guide. Let's roughly copy the code from there and adapt to Vue:

https://github.com/TanStack/store/blob/main/docs/framework/react/quick-start.md

Thank you for helping! :D

**Comment by Davidthecode** [comment]
Hi @crutchcorn, thanks for your feedback, I thought you had the code for the vue component, i use react not vue

**Comment by nathantaal** [comment]
Since it's seems a PR doing this has been merged, I think this issue can be closed?
