### ISSUE TITLE
Docs: Quick start and useStore API reference page for react are broken

### ISSUE THREAD

**Issue by sadik-malik** [TanStack/store#32]
### Describe the bug

1. Quick start page for react is not opening, the page is stuck on displaying infinite spinning loader.
2. Codesandbox link for react example of useStore is not found.

### Your Example Website or App

https://tanstack.com/store/latest/docs/framework/react/reference/useStore

### Steps to Reproduce the Bug or Issue

Refer the image for both the problems. I have first opened the useStore react example and then clicked on Quick start for react. You can see both not found error and infinite spinning loader in the image.

### Expected behavior

1. When clicked on quick start for react, the page display documentation on how to use TanStack Store in react instead of infinite spinning loader.
2. Codesandbox example should display Tanstack Store usage in react instead of 404 error.

### Screenshots or Videos

![image](https://github.com/TanStack/store/assets/38027249/395223ae-265b-4abb-984a-b24f821c9199)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 120.0.6099.72 (Official Build) (64-bit)

**Comment by crutchcorn** [comment]
This is my bad. This was my first TanStack project I launched and I didn't have any examples in the repo to support this. I'll add some examples early next year

**Comment by ImLunaHey** [comment]
Until this is resolved it looks like https://github.com/TanStack/store/blob/main/docs/framework/react/quick-start.md is the correct file.

**Comment by sadik-malik** [comment]
Thank you @ImLunaHey

> Until this is resolved it looks like https://github.com/TanStack/store/blob/main/docs/framework/react/quick-start.md is the correct file.

**Comment by yoosion030** [comment]
Hello, @sadik-malik .
Has the issue of not adding examples been resolved yet?
I can't find examples in the docs and codebox. I'm curious and looking forward to seeing what tanstack/store does :)

https://tanstack.com/store/latest/docs/framework/react/examples/simple

https://github.com/TanStack/store/assets/80191860/33a9a4dc-f31d-4c99-8743-2ac3bc7b4687

**Comment by sadik-malik** [comment]
@yoosion030 the issue is not fixed. You can refer to the quick start guide.

https://github.com/TanStack/store/blob/main/docs/framework/react/quick-start.md

**Comment by crutchcorn** [comment]
This is now fixed alongside a few improvements, namely:

- Reference docs are auto-generated from the code (so they cannot get outdated)
- Examples in all supported frameworks are now live
