### ISSUE TITLE
Solid Adapter

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/store#5]
It would be really cool to see a [Solid](https://www.solidjs.com/) adapter for this project. I have a few questions I'm unclear about that would need to be solved:

- Packaging
- Testing ([Testing Library](https://github.com/solidjs/solid-testing-library)?)
- Reactivity interop

Ideally the API should look nearly identical [to the React API](https://github.com/TanStack/store/blob/d4bd1d76b0e73450666e607f5ee1d9028f0b1b44/packages/react-store/src/tests/index.test.tsx#L12-L26)

**Comment by wobsoriano** [comment]
I can think of 2 ways on implementing this:

1. Use the `shallow` function we have in both React and Vue adapters, and pass it to [createSignal](https://www.solidjs.com/docs/latest#options) as diff function:

```tsx
import { createSignal, onCleanup } from 'solid-js'

export function useStore(store, selector:) {
  const [slice, setSlice] = createSignal(selector(store.state), {
    equals: shallow, // Pass the shallow function here for testing equality.
  })

  const unsub = store.subscribe(() => {
    const data = selector(store.state)
    setSlice(data)
  })

  onCleanup(() => {
    unsub()
  })

  return slice
}
```

2. Take advantage of Solid's built-in [stores](https://www.solidjs.com/docs/latest#stores)

```tsx
import { onCleanup } from 'solid-js'
import { createStore, reconcile } from 'solid-js/store'

export function useStore(store, selector) {
  const [slice, setSlice] = createStore({
    value: selector(store.state)
  })

  const unsub = store.subscribe(() => {
    const data = selector(store.state)
    setSlice('value', reconcile(data)) // recursive diff on the new value
  })

  onCleanup(() => {
    unsub()
  })

  return () => slice.value
}
```

**Comment by tannerlinsley** [comment]
I thought about this a lot and even gone down very dangerous paths with Ryan Carniato talking about how we can bridge the gap between signals and immutable values. The only secure place that I’ve landed is that reconcile is the answer.

**Comment by wobsoriano** [comment]
If ever number 2 from my comment would work, I can open a PR with some tests 👍🏼

**Comment by tannerlinsley** [comment]
The selector could be optional at that point since you wouldn’t need it for fine grained subscriptions, its only purpose would be to maybe cut down on the amount of work that reconcile has to do. Thoughts?

**Comment by Tanner-Scadden** [comment]
https://github.com/TanStack/router/pull/671/files#diff-9be81768de8c03b212d1afde126315756a7ad4dccc75840d1925a58973238923

Here is a PR I've been working on slowly where I have a working solid version. Would love any feedback on my choice. It's assigned to `routerStore` because the selector value could be a string/number/etc. 
 
The shallowFindMissingKeys function was to help remove values that were previously there in the case of url search params being removed.

**Comment by wobsoriano** [comment]
> The selector could be optional at that point

Can you elaborate on this @tannerlinsley? If I understand correctly, you meant removing the selector? So if you want to do data transform, you do it outside the primitive?

**Comment by tannerlinsley** [comment]
Something like this:

```tsx
import { onCleanup } from 'solid-js'
import { createStore, reconcile } from 'solid-js/store'

const defaultSelector = <T>(state: T): T => state

export function useStore<TState, TSelected = TState>(store: Store<TState>, selector?: (state: TState) => TSelected): TSelected {
  selector = selector || (defaultSelector as any)

  const [slice, setSlice] = createStore({
    value: selector(store.state)
  })

  const unsub = store.subscribe(() => {
    const newValue = selector(store.state)
    setSlice('value', reconcile(newValue)) // recursive diff on the new value
  })

  onCleanup(() => {
    unsub()
  })

  return () => slice.value
}
```

**Comment by wobsoriano** [comment]
Aight, that makes sense @tannerlinsley! Thanks.
