### ISSUE TITLE
Documentation says library is compatible with React 16.8.0, but peerDependencies is `{ "react": "^17.0.0 || ^18.0.0", "react-dom": "^17.0.0 || ^18.0.0" }`

### ISSUE THREAD

**Issue by cristiano-belloni** [TanStack/store#54]
### Describe the bug

From package.json of 0.3.1:

```
"peerDependencies": {
    "react": "^17.0.0 || ^18.0.0",
    "react-dom": "^17.0.0 || ^18.0.0"
  },
```

### Steps to Reproduce the Bug or Issue

- Try to install the library in a project that has react 16 (> 16.8.0):

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0 || ^18.0.0" from @tanstack/react-store@0.3.1
npm ERR! node_modules/@tanstack/react-store
npm ERR!   @tanstack/react-store@"*" from the root project
```

### Expected behavior

As per README, I'd expect the package to be installed without peer dependencies conflict.

### Platform

- OS: Windows
- Browser: N/A, this is a dependency issue
- Version: N/A, this is a dependency issue

**Comment by crutchcorn** [comment]
Thanks for the report!

The `package.json` has been updated to include `16.8.0` and `19` as well as-of `0.6.1`

Sorry it took so long to fix.
