### ISSUE TITLE
Write React Quick Start Guide

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/store#6]
We should have an early Quick Start guide [in the style of our Forms docs](https://tanstack.com/form/latest/docs/framework/react/quick-start) that includes a demo codebase for `store` like a counter or something similar.

File to edit: https://github.com/TanStack/store/blob/main/docs/framework/react/quick-start.md

**Comment by VikasSherawat** [comment]
@crutchcorn

I am picking this one first.
