### ISSUE TITLE
Write React Reference Docs

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/store#9]
We should have an early Reference doc [in the style of our Forms docs](https://tanstack.com/form/latest/docs/framework/react/reference/useField) that includes:

- `useStore` hook
    - Passed properties
    - Return type

File to edit: https://github.com/TanStack/store/blob/main/docs/framework/react/reference/useStore.md

**Comment by VikasSherawat** [comment]
@crutchcorn 
Working on this doc as well.
